# Generated by Django 4.0.6 on 2024-05-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0003_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
