# Generated by Django 4.0.6 on 2024-08-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0008_cine_director_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cascada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('altura', models.BooleanField(default=True)),
                ('agua', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(max_length=150)),
                ('acceso', models.CharField(max_length=75)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='cascadas')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartelera.cascada'),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
