databases:
  - name: servidorAli
    plan: free
    databaseName: dbcine #no mayusculas
    user: alison

services:
  - type: web
    plan: free
    name: cineUTC
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUTC.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorAli
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutc-mb47.onrender.com

# set DATABASE_URL=postgresql://alison:sZchGI7cI1xLRjCTWj2AHxhBEI6MkUNF@dpg-cqlqr6g8fa8c73bnnnug-a.oregon-postgres.render.com/dbcine_nezy